disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - identifier_name
included:
excluded:
  - Carthage
  - Pods
  - R.generated.swift

trailing_whitespace:
  severity: error
operator_whitespace:
  severity: error
colon:
  severity: error
vertical_whitespace:
  severity: error
unused_closure_parameter:
  severity: error
force_try:
  severity: error
type_body_length:
  warning: 100
  error: 200
function_body_length:
  warning: 10
  error: 20
cyclomatic_complexity:
  warning: 5
  error: 10
nesting:
  statement_level:
    warning: 3
function_parameter_count:
  warning: 4
  error: 5
file_length:
  warning: 200
  error: 400
line_length:
  warning: 120
  error: 130

